손가영-백엔드-5주차 장고 DRF과제
likelion-Inha-12/gayo73 pull request #9
Opened 2024-05-04 14:40 UTC by gayo73

https://mire-rake-093.notion.site/70241bd94f0f4ff8b464ffe90835b946?pvs=4
키워드 과제 노션입니다!

2024-05-06 11:29 UTC, kseysh commented
스크린샷 여기 코멘트에 달아주실 수 있으실까요?? PR에서 안보여요 ㅠㅠ
그리고 .gitignore에 `__pycache__`를 추가해서 PR에 올라가지 않도록 해주세요!

2024-05-07 02:01 UTC, gayo73 commented
<img width="1470" alt="스크린샷 2024-05-04 오후 9 31 33" src="https://github.com/likelion-Inha-12/gayo73/assets/163620291/7e517eee-f49a-407f-91b5-d65fc0194db4">
<img width="1470" alt="스크린샷 2024-05-04 오후 10 31 08" src="https://github.com/likelion-Inha-12/gayo73/assets/163620291/27132676-ef0a-4c9c-8728-2628514ddbeb">
<img width="1470" alt="스크린샷 2024-05-04 오후 10 31 42" src="https://github.com/likelion-Inha-12/gayo73/assets/163620291/81c19f79-ad12-4bcc-9141-771bde3af3dc">
<img width="1470" alt="스크린샷 2024-05-04 오후 10 36 05" src="https://github.com/likelion-Inha-12/gayo73/assets/163620291/76222458-df01-4d95-bdf6-b84e7d95671c">
<img width="1470" alt="스크린샷 2024-05-04 오후 10 36 47" src="https://github.com/likelion-Inha-12/gayo73/assets/163620291/a89a04cf-687d-4c49-bea1-bb9d44cdc4a0">

2024-05-07 02:02 UTC, gayo73 commented
사진 파일을 빼놓고 경로만 올렸네요..죄송합니다! 다음부터 .gitignore도 주의하겠습니다

2024-05-07 07:15 UTC, kseysh requested changes
`.gitignore`에 `__pycache__`가 없는 것 같아요! 수정해서 여기 Files changed에 github에 올리기 불필요한 파일들을 지워주세요!

2024-05-07 07:29 UTC, gayo73 commented
수정했습니다!!

2024-05-07 07:34 UTC, kseysh commented
아래 사진에 보면 Files changed에 가보면 아직 `__pycache__`폴더 안의 파일이 남아있어요! 
<img width="1710" alt="image" src="https://github.com/likelion-Inha-12/gayo73/assets/69035864/dcee827a-1fa7-43df-a208-b25eb98748cd">

아래 참고해서 삭제 이후에 다시 PR 올려보셔요~
**[[참고한 블로그]](https://tychejin.tistory.com/231)**
<img width="817" alt="image" src="https://github.com/likelion-Inha-12/gayo73/assets/69035864/cf81a73f-2017-4bc4-8953-f99647a3e587">

2024-05-08 08:50 UTC, gayo73 commented
올려주신 블로그대로 했는데 파일이 안보이나요..? 저한텐 .gitignore 처리된 파일들도 다 보이는 것 같아요ㅠㅠ

2024-05-09 09:37 UTC, kseysh approved these changes

2024-05-13 11:25 UTC, merged